# Generated by Django 5.0.7 on 2024-07-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0003_cliente_language_cliente_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='language',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='newsletter',
        ),
    ]
