# Generated by Django 5.0.7 on 2024-07-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0004_remove_cliente_language_remove_cliente_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='optica.cliente'),
        ),
    ]
