# Generated by Django 5.0.7 on 2024-07-17 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dv',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message="El dígito verificador debe ser un número o 'K'", regex='^[0-9kK]{1}$')]),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
