# Generated by Django 5.0.7 on 2024-07-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0008_remove_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='potica/images'),
        ),
    ]
